version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: *
        update-types: [ "version-update:semver-major" ]
