name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  forge-test:
    name: Foundry test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge dependencies
        run: forge install

      - name: Run Forge tests
        run: forge test -vvv

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-concurrency 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge dependencies
        run: forge install

      - name: Compile contracts
        run: yarn compile

      - name: Build dist files
        run: yarn build

      - name: Pack NPM package
        run: npm pack
